### ISSUE TITLE
SetContentSize destroys Layout if CanvasScaler is used

### ISSUE THREAD

**Issue by Noshire** [taka-oyama/ScrollSnap#4]
`	private void SetContentSize(int elementCount) {
		this.content.sizeDelta = new Vector2(this.cellSize.x * elementCount, this.content.rect.height);
	}`

can set content RectTransform to a wrong height if a CanvasScaler is used on the root canvas. To fix this, change it to:

`	private void SetContentSize(int elementCount) {
		this.content.sizeDelta = new Vector2(this.cellSize.x * elementCount, this.content.sizeDelta.y);
	}`

**Comment by taka-oyama** [comment]
Can't reproduce. I will close this for now.
Please elaborate if it's still a problem.
