### ISSUE TITLE
CalculateMaxIndex off by 1

### ISSUE THREAD

**Issue by Noshire** [taka-oyama/ScrollSnap#5]
CalculateMaxIndex returns the count of child LayoutElements. Since it represents a 0-based index, however, this would for example return **5** for a collection of **5** elements, where the MaxIndex should actually be **4** (0,1,2,3,4).

**Comment by scorp-3d** [comment]
I encountered an issue "Jerk On Last Element". I found solution of it.

Script - ScrollSnap.cs
Line 154 => 			newCellIndex = Mathf.Clamp(newCellIndex, 0, maxIndex-1);

![image](https://user-images.githubusercontent.com/5173641/64251219-97e38f00-cf35-11e9-9d8c-6a59bd449d5b.png)

**Comment by taka-oyama** [comment]
Thanks for commenting.
I never encountered this problem with the example.
